// swift-tools-version: 6.2
import PackageDescription

// Platform-independent core of Pixel Open Space: builds and tests on Linux and macOS.
// The macOS app (App/, generated by XcodeGen from project.yml) depends on PixelCore and PixelIPC,
// and embeds the pixel-hook executable in its bundle.
let package = Package(
    name: "PixelCore",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "PixelCore", targets: ["PixelCore"]),
        .library(name: "PixelIPC", targets: ["PixelIPC"]),
        .executable(name: "pixel-hook", targets: ["pixel-hook"]),
        .executable(name: "fake-claude", targets: ["fake-claude"]),
    ],
    targets: [
        .target(name: "PixelIPC"),
        .target(name: "PixelCore", dependencies: ["PixelIPC"]),
        .executableTarget(name: "pixel-hook", dependencies: ["PixelIPC"]),
        .executableTarget(name: "fake-claude", dependencies: ["PixelIPC"]),
        .testTarget(
            name: "PixelCoreTests",
            dependencies: ["PixelCore"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "PixelIPCTests",
            dependencies: ["PixelIPC", "PixelCore", "pixel-hook", "fake-claude"]
        ),
    ]
)
